sudo: required
services:
  - docker

before_install:
  - docker build -t shbaek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shbaek/react-test npm test

after_success:
  - docker build -t shbaek/multi-client ./client
  - docker build -t shbaek/multi-nginx ./nginx
  - docker build -t shbaek/multi-server ./server
  - docker build -t shbaek/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shbaek/multi-client
  - docker push shbaek/multi-nginx 
  - docker push shbaek/multi-server
  - docker push shbaek/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-954155194025
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY